### PR TITLE
Release/staging

### PR DESCRIPTION
**Pull request by Hariharan148**

### CODE REVIEW

**Comment by VikashPR** [comment]
@Hariharan148 Serve the project locally and check once, We will merge it to production

**Comment by Hariharan148** [comment]
> @Hariharan148 Serve the project locally and check once, We will merge it to production

tested locally, just testing whether it is deploying in netlify when code is merged

**Comment by VikashPR** [comment]
> > @Hariharan148 Serve the project locally and check once, We will merge it to production
> 
> tested locally, just testing whether it is deploying in netlify when code is merged

I don't think it is deploying.

**Comment by Hariharan148** [comment]
> > > @Hariharan148 Serve the project locally and check once, We will merge it to production
> > 
> > 
> > tested locally, just testing whether it is deploying in netlify when code is merged
> 
> I don't think it is deploying.

ya i need to add an nvmrc file, i missed it

**Pull request closed without merging**
